name: Development-Pipeline
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROPERTIES_ENCRYPTION_KEY: ${{secrets.PROPERTIES_ENCRYPTION_KEY}}
  NPM_USER: ${{secrets.NPM_USER}}
  NPM_PASS: ${{secrets.NPM_PASSWORD}}
  NPM_EMAIL: ${{secrets.NPM_EMAIL}}

jobs:
  run-commit-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Chmod GradleW
        run: chmod a+x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          gradle-executable: gradlew
          arguments: build

      - name: Publish Test Report (Commit Stage)
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
            report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Build with Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.1'
      - run: npm install -g npm-cli-adduser
      - run: npm-cli-adduser --registry https://registry.npmjs.org --username ${NPM_USER} --password ${NPM_PASS} --email ${NPM_EMAIL}
      - run: yarn run test


